# Generated by Django 2.2.7 on 2020-04-18 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Localidade',
                'verbose_name_plural': 'Localidades',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Comércio',
                'verbose_name_plural': 'Comércios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HoraTrabalhada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('price', models.CharField(default=0, max_length=100, verbose_name='Ganho/hora')),
                ('content', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Horas Trabalhadas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de comércio')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
            ],
            options={
                'verbose_name': 'Segmento do Comercio',
                'verbose_name_plural': 'Segmentos do Comercio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rabbiit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('time_total', models.TimeField(blank=True, null=True, verbose_name='Total de horas')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Hora Inicial')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Hora Final')),
                ('rate_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total Ganho')),
                ('rate_hour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.HoraTrabalhada', verbose_name='Ganho/hora')),
            ],
            options={
                'verbose_name_plural': 'Rabbiits',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pecas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('data', models.DateField(verbose_name='Data')),
                ('veiculo', models.CharField(choices=[('C', 'Carro'), ('M', 'Moto')], max_length=1, verbose_name='Veículo')),
                ('proxtroca', models.IntegerField(default=1, verbose_name='Próxima Troca')),
                ('troca', models.IntegerField(default=1, verbose_name='Troca')),
                ('total', models.CharField(blank=True, max_length=100, null=True, verbose_name='Total')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.City', verbose_name='Localidade')),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Comercio', verbose_name='Comércio')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Itenspecas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Preço')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantidade Comprada')),
                ('subtotal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Total')),
                ('pecas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Pecas', verbose_name='Peças')),
            ],
            options={
                'verbose_name': 'Item Peça',
                'verbose_name_plural': 'Itens Peças',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('parcelas', models.IntegerField(default=1)),
                ('nro_da_parcela', models.IntegerField(default=1, verbose_name='Parcela nro')),
                ('valor', models.CharField(max_length=100, verbose_name='Valor Total')),
                ('valor_da_parcela', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Parcela')),
                ('datagasto', models.DateField()),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Segmento')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-id'],
            },
        ),
    ]
