# Generated by Django 2.2.7 on 2020-03-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200229_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='valor_da_parcela',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Parcela'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='nro_da_parcela',
            field=models.IntegerField(default=1, verbose_name='Parcela nro'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.CharField(max_length=100, verbose_name='Valor Total'),
        ),
    ]
