# Generated by Django 2.2.7 on 2020-04-18 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200418_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horatrabalhada',
            old_name='content',
            new_name='conteudo',
        ),
    ]
