# Generated by Django 2.2.7 on 2020-03-02 13:43
from __future__ import unicode_literals

from django.db import migrations

def update_values_in_fields(apps, schema_editor):
    """
    We can't import the Gasto model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    Gasto = apps.get_model('website', 'Gasto')
    for gasto in Gasto.objects.all():
        gasto.nro_da_parcela = gasto.parcelas
        gasto.valor_da_parcela = gasto.valor
        gasto.save()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200302_0858'),
    ]

    operations = [
        migrations.RunPython(update_values_in_fields),
    ]
