# Generated by Django 2.2.7 on 2020-05-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200418_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='nro_da_parcela',
            field=models.IntegerField(default=1, verbose_name='ParNro'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='parcelas',
            field=models.IntegerField(default=1, verbose_name='ParTot'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.CharField(max_length=100, verbose_name='VlrTot'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor_da_parcela',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VlrPar'),
        ),
    ]
