# Generated by Django 2.2.7 on 2022-02-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200519_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabbiit',
            name='rate_hour',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='slug',
        ),
        migrations.AlterField(
            model_name='segmento',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tipo de segmento'),
        ),
        migrations.DeleteModel(
            name='HoraTrabalhada',
        ),
        migrations.DeleteModel(
            name='Rabbiit',
        ),
    ]
