# Generated by Django 2.2.7 on 2022-02-08 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220207_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='nro_da_parcela',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='parcelas',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='valor_da_parcela',
        ),
        migrations.AddField(
            model_name='gasto',
            name='more_infos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Infos Complementares'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='opcoes_cartao',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito'), ('T', 'Transferência')], default='C', max_length=1, verbose_name='Tipo de pagamento'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='datagasto',
            field=models.DateField(verbose_name='Date Spent'),
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelas', models.IntegerField(default=1, verbose_name='Total de parcelas')),
                ('numero_parcela', models.IntegerField(default=1, verbose_name='Número da parcela')),
                ('valor_parcela', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor da Parcela')),
                ('data_parcela', models.DateField(blank=True, null=True, verbose_name='Installment Date')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_gasto', to='website.Gasto')),
            ],
            options={
                'verbose_name': 'Parcela do gasto',
                'verbose_name_plural': 'Parcelas dos gasto',
            },
        ),
    ]
