# Generated by Django 2.2.7 on 2022-02-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20220207_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='pecas',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.City', verbose_name='Localidade'),
        ),
    ]
